const SET_TOP_HIGHLIGHT = 'SET_TOP_HIGHLIGHT';
const SET_LOADING = 'SET_LOADING';
const SET_SOURCES = 'SET_SOURCES';
const SET_SOURCES_FILTER = 'SET_SOURCES_FILTER';
const SET_QUERY = 'SET_QUERY';
const RESET_STATE = 'RESET_STATE';
const ADD_HISTORY = 'ADD_HISTORY';

export {
  ADD_HISTORY,
  SET_TOP_HIGHLIGHT,
  SET_SOURCES_FILTER,
  SET_QUERY,
  SET_LOADING,
  SET_SOURCES,
  RESET_STATE,
};
